ERROR - 2023-11-20 04:16:00 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(132): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:16:00 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(132): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:19:52 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:19:52 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:20:40 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:20:40 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:20:57 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:20:57 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:22:06 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\laragon\www\backend\system\BaseModel.php(698): CodeIgniter\Model->insert(Array, false)
#8 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\BaseModel->save(Array)
#9 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#10 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#11 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#13 {main}
CRITICAL - 2023-11-20 04:22:06 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(698): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\MainController.php(133): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 8 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 9 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:29:34 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:29:34 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:36:49 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:36:49 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:37:27 --> Attempt to read property "ENTRY_ID" on null
in APPPATH\Controllers\MainController.php on line 115.
 1 APPPATH\Controllers\MainController.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "ENTRY_ID" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 115)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:37:35 --> Attempt to read property "ENTRY_ID" on null
in APPPATH\Controllers\MainController.php on line 115.
 1 APPPATH\Controllers\MainController.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "ENTRY_ID" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 115)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:38:17 --> Attempt to read property "ENTRY_ID" on null
in APPPATH\Controllers\MainController.php on line 115.
 1 APPPATH\Controllers\MainController.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "ENTRY_ID" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 115)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:39:02 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:39:02 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:39:46 --> Attempt to read property "details" on null
in APPPATH\Controllers\MainController.php on line 115.
 1 APPPATH\Controllers\MainController.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "details" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 115)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:39:56 --> Attempt to read property "full_name" on null
in APPPATH\Controllers\MainController.php on line 116.
 1 APPPATH\Controllers\MainController.php(116): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "full_name" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 116)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:40:44 --> Attempt to read property "full_name" on null
in APPPATH\Controllers\MainController.php on line 116.
 1 APPPATH\Controllers\MainController.php(116): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "full_name" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 116)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:40:50 --> Attempt to read property "ENTRY_ID" on null
in APPPATH\Controllers\MainController.php on line 115.
 1 APPPATH\Controllers\MainController.php(115): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "ENTRY_ID" on null', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 115)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-11-20 04:43:13 --> Undefined property: CodeIgniter\HTTP\IncomingRequest::$full_name
in APPPATH\Controllers\MainController.php on line 116.
 1 APPPATH\Controllers\MainController.php(116): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: CodeIgniter\\HTTP\\IncomingRequest::$full_name', 'C:\\laragon\\www\\backend\\app\\Controllers\\MainController.php', 116)
 2 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 3 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 4 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:47:22 --> mysqli_sql_exception: Unknown column 'NAME_0F_VALIDATOR' in 'field list' in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(149): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:47:22 --> Unknown column 'NAME_0F_VALIDATOR' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_0F_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_0F_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(149): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 04:48:39 --> mysqli_sql_exception: Column 'ENTRY_ID' cannot be null in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(149): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 04:48:39 --> Column 'ENTRY_ID' cannot be null
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(149): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 10:59:53 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 10:59:53 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:01:42 --> mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1 in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:01:42 --> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '))' at line 1
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:09:45 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:09:45 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:18:30 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:18:30 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:26:17 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:26:17 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:26:43 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:26:43 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:26:47 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:26:47 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
ERROR - 2023-11-20 11:27:09 --> mysqli_sql_exception: Operand should contain 1 column(s) in C:\laragon\www\backend\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\laragon\www\backend\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `en...', 0)
#1 C:\laragon\www\backend\system\Database\BaseConnection.php(692): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `en...')
#2 C:\laragon\www\backend\system\Database\BaseConnection.php(606): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `en...')
#3 C:\laragon\www\backend\system\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `en...', Array, false)
#4 C:\laragon\www\backend\system\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\backend\system\BaseModel.php(788): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\backend\system\Model.php(715): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\backend\app\Controllers\MainController.php(133): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\backend\system\CodeIgniter.php(919): App\Controllers\MainController->insert()
#9 C:\laragon\www\backend\system\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
#10 C:\laragon\www\backend\system\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\backend\public\index.php(85): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2023-11-20 11:27:09 --> Operand should contain 1 column(s)
in SYSTEMPATH\Database\BaseConnection.php on line 646.
 1 SYSTEMPATH\Database\BaseBuilder.php(2308): CodeIgniter\Database\BaseConnection->query('INSERT INTO `encoder` (`ENTRY_ID`, `GRANTEE_NAME`, `MUNICIPALITY`, `HH_ID`, `BRGY`, `HH_STATUS`, `VALIDATED`, `WITH_VALIDATION_TOOL`, `WITH_UPDATE_REQUEST`, `DATE_VALIDATED`, `NAME_OF_VALIDATOR`, `SUBMITTED`, `DATE_SUBMITTED`, `ENCODED_IN_PPIS/MCCTIS`, `TYPES_OF_UPDATE/S_FIELD`) VALUES (:ENTRY_ID:, :GRANTEE_NAME:, :MUNICIPALITY:, :HH_ID:, :BRGY:, :HH_STATUS:, :VALIDATED:, :WITH_VALIDATION_TOOL:, :WITH_UPDATE_REQUEST:, :DATE_VALIDATED:, :NAME_OF_VALIDATOR:, :SUBMITTED:, :DATE_SUBMITTED:, :ENCODED_IN_PPIS/MCCTIS:, :TYPES_OF_UPDATE/S_FIELD:)', [...], false)
 2 SYSTEMPATH\Model.php(319): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(788): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(715): CodeIgniter\BaseModel->insert([...], true)
 5 APPPATH\Controllers\MainController.php(133): CodeIgniter\Model->insert([...])
 6 SYSTEMPATH\CodeIgniter.php(919): App\Controllers\MainController->insert()
 7 SYSTEMPATH\CodeIgniter.php(494): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\MainController))
 8 SYSTEMPATH\CodeIgniter.php(353): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(85): CodeIgniter\CodeIgniter->run()
